### ISSUE TITLE
Error with training the sample data

### ISSUE THREAD

**Issue by KH-Kyle** [personalrobotics/pytorch_retinanet#5]
I changed `<src/pytorch_retinanet/config/config.py>` with `<img_res = 300>` and `<num_classes = 3>`. When I run `<./train.py>`, it shows:

Load ListDataset

Epoch: 0
/usr/local/lib/python3.5/dist-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "./train.py", line 164, in <module>
    run_train()
  File "./train.py", line 159, in run_train
    train(epoch)
  File "./train.py", line 109, in train
    loss = criterion(loc_preds, loc_targets, cls_preds, cls_targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guohaz/retinanet/pytorch_retinanet/src/pytorch_retinanet/loss/focal_loss.py", line 47, in forward
    cls_loss = self.focal_loss(m_cls_preds, cls_targets[pos_neg])
  File "/home/guohaz/retinanet/pytorch_retinanet/src/pytorch_retinanet/loss/focal_loss.py", line 22, in focal_loss
    t = one_hot_embedding(y.data, 1 + config.num_classes)  # [N,21]
  File "/home/guohaz/retinanet/pytorch_retinanet/src/pytorch_retinanet/utils/pt_utils.py", line 239, in one_hot_embedding
    return y[labels]            # [N,D]
IndexError: index 950 is out of bounds for dimension 0 with size 4

**Comment by KH-Kyle** [comment]
> I changed `<src/pytorch_retinanet/config/config.py>` with `<img_res = 300>` and `<num_classes = 3>`. When I run `<./train.py>`, it shows:
> 
> Load ListDataset
> 
> Epoch: 0
> /usr/local/lib/python3.5/dist-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
> warnings.warn(warning.format(ret))
> Traceback (most recent call last):
> File "./train.py", line 164, in 
> run_train()
> File "./train.py", line 159, in run_train
> train(epoch)
> File "./train.py", line 109, in train
> loss = criterion(loc_preds, loc_targets, cls_preds, cls_targets)
> File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/guohaz/retinanet/pytorch_retinanet/src/pytorch_retinanet/loss/focal_loss.py", line 47, in forward
> cls_loss = self.focal_loss(m_cls_preds, cls_targets[pos_neg])
> File "/home/guohaz/retinanet/pytorch_retinanet/src/pytorch_retinanet/loss/focal_loss.py", line 22, in focal_loss
> t = one_hot_embedding(y.data, 1 + config.num_classes) # [N,21]
> File "/home/guohaz/retinanet/pytorch_retinanet/src/pytorch_retinanet/utils/pt_utils.py", line 239, in one_hot_embedding
> return y[labels] # [N,D]
> IndexError: index 950 is out of bounds for dimension 0 with size 4

**Comment by youngsunkim** [comment]
Please check which dataset you are using and its format. You might need to change the value of `isize` here:
https://github.com/personalrobotics/pytorch_retinanet/blob/a49b3299644c6dd3c6e0510834e7fa0c3c6fc2cf/src/pytorch_retinanet/model/retinanet_dataset.py#L47

**Comment by KH-Kyle** [comment]
Thank you! It works. However, it gives me a new error:

Epoch: 0
/usr/local/lib/python3.5/dist-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "./train.py", line 165, in <module>
    run_train()
  File "./train.py", line 160, in run_train
    train(epoch)
  File "./train.py", line 110, in train
    loss = criterion(loc_preds, loc_targets, cls_preds, cls_targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guohaz/retinanet/pytorch_retinanet/src/pytorch_retinanet/loss/focal_loss.py", line 47, in forward
    cls_loss = self.focal_loss(m_cls_preds, cls_targets[pos_neg])
  File "/home/guohaz/retinanet/pytorch_retinanet/src/pytorch_retinanet/loss/focal_loss.py", line 31, in focal_loss
    return F.binary_cross_entropy_with_logits(x, t, w, size_average=False)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 2157, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: the derivative for 'weight' is not implemented

**Comment by yskim041** [comment]
I found that the behavior of the `torch.nn.functional.binary_cross_entorpy_with_logits` was changed since PyTorch 1.0. I fixed the issue in PR #6 .
